import AppKit
import Foundation
import RayPlacementCore

@MainActor
final class ClipboardHistoryService: ObservableObject {
    static let shared = ClipboardHistoryService()
    @Published private(set) var entries: [ClipboardEntry] = []
    @Published var lastError: String?
    @Published private(set) var recoveryURL: URL?

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var settingsObserver: NSObjectProtocol?
    private let fileStore = PrivateFileStore()
    private let persistenceQueue = DispatchQueue(label: "dev.rayplacement.clipboard-persistence", qos: .utility)
    private let maxEntryCharacters = 20_000
    private let maxTotalCharacters = 1_000_000
    private let excludedTypes = Set([
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.agilebits.onepassword.private"
    ])

    init() {
        load()
        applySettings()
        settingsObserver = NotificationCenter.default.addObserver(
            forName: .rayPlacementClipboardSettingsChanged,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { @MainActor in self?.applySettings() }
        }
    }

    deinit {
        timer?.invalidate()
        if let settingsObserver { NotificationCenter.default.removeObserver(settingsObserver) }
    }

    func replace(with replacement: [ClipboardEntry]) throws {
        guard replacement.count <= 500 else {
            throw NSError(domain: "LimaClipboard", code: 1, userInfo: [NSLocalizedDescriptionKey: "The imported clipboard history is too large."])
        }
        entries = replacement.map { ClipboardEntry(id: $0.id, text: String($0.text.prefix(maxEntryCharacters)), capturedAt: $0.capturedAt, pinned: $0.pinned) }
        _ = enforceLimits()
        save()
        lastError = nil
    }

    func applySettings() {
        timer?.invalidate()
        timer = nil
        if enforceLimits() { save() }
        guard SettingsStore.shared.clipboardEnabled else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.8, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.captureIfNeeded() }
        }
    }

    func copy(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        if SettingsStore.shared.clipboardEnabled { insert(text) }
    }

    func synchronizePasteboardChangeCount() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func clear() {
        entries.removeAll()
        save()
        flush()
    }

    func flush() {
        persistenceQueue.sync {}
    }

    private func captureIfNeeded() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        let typeNames = Set((pasteboard.types ?? []).map(\.rawValue))
        guard excludedTypes.isDisjoint(with: typeNames) else { return }
        guard let text = pasteboard.string(forType: .string) else { return }
        insert(text)
    }

    private func insert(_ rawText: String) {
        let text = String(rawText.trimmingCharacters(in: .newlines).prefix(maxEntryCharacters))
        guard !text.isEmpty else { return }
        entries.removeAll { $0.text == text }
        entries.insert(ClipboardEntry(text: text), at: 0)
        _ = enforceLimits()
        save()
    }

    private func load() {
        let loaded = fileStore.loadJSON([ClipboardEntry].self, from: ApplicationPaths.clipboardHistory)
        guard let decoded = loaded.value else {
            guard loaded.result.state != .missing else { return }
            lastError = "Clipboard history could not be loaded safely. The original file was preserved."
            recoveryURL = loaded.result.recoveryURL
            return
        }
        let limit = SettingsStore.shared.clipboardLimit
        let needsRewrite = decoded.count > limit || decoded.contains { $0.text.count > maxEntryCharacters }
        entries = decoded.prefix(limit).map { entry in
            ClipboardEntry(id: entry.id, text: String(entry.text.prefix(maxEntryCharacters)), capturedAt: entry.capturedAt, pinned: entry.pinned)
        }
        if needsRewrite || enforceLimits() { save() }
    }

    private func save() {
        let snapshot = entries
        persistenceQueue.async {
            do {
                let data = try JSONEncoder().encode(snapshot)
                try self.fileStore.write(data: data, to: ApplicationPaths.clipboardHistory)
                DispatchQueue.main.async { [weak self] in self?.lastError = nil }
            } catch {
                DispatchQueue.main.async { [weak self] in self?.lastError = error.localizedDescription }
            }
        }
    }

    @discardableResult
    private func enforceLimits() -> Bool {
        let originalCount = entries.count
        let countLimit = SettingsStore.shared.clipboardLimit
        if entries.count > countLimit { entries.removeLast(entries.count - countLimit) }

        var totalCharacters = entries.reduce(0) { $0 + $1.text.count }
        while totalCharacters > maxTotalCharacters, let last = entries.last {
            totalCharacters -= last.text.count
            entries.removeLast()
        }
        return entries.count != originalCount
    }
}
