#!/bin/zsh
# Generate a Sparkle 2-compatible appcast as a migration artifact. Lima's
# active updater does not consume this file yet; it is intentionally generated
# from the same immutable release metadata as latest.json.
set -euo pipefail

METADATA=""
OUTPUT=""
while (( $# > 0 )); do
    case "$1" in
        --metadata) METADATA="${2:?--metadata requires a file}"; shift 2;;
        --output) OUTPUT="${2:?--output requires a file}"; shift 2;;
        -h|--help)
            print 'Usage: generate_sparkle_appcast.sh --metadata dist/Lima-release.json --output dist/appcast.xml'
            exit 0;;
        *) print -u2 "Unknown option: $1"; exit 2;;
    esac
done
[[ -f "$METADATA" && -n "$OUTPUT" ]] || { print -u2 'Metadata and output are required.'; exit 2; }

version="$(jq -er '.version' "$METADATA")"
tag="$(jq -er '.tag' "$METADATA")"
release_url="$(jq -er '.releaseUrl' "$METADATA")"
update_url="$(jq -er '.updateUrl' "$METADATA")"
update_sha="$(jq -er '.update.sha256' "$METADATA")"
update_bytes="$(jq -er '.update.bytes' "$METADATA")"
generated_at="$(jq -er '.generatedAt' "$METADATA")"

# XML is emitted with shell-safe values after validating the release metadata.
# Version and URLs are generated by the repository's fixed URL templates; escape
# the values anyway so this remains safe if the schema gains a custom title.
xml_escape() {
    print -r -- "$1" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&apos;/g'
}
mkdir -p "${OUTPUT:h}"
{
    print '<?xml version="1.0" encoding="utf-8"?>'
    print '<rss version="2.0" xmlns:sparkle="http://www.andymatushek.org/xml-namespaces/sparkle" xmlns:lima="https://www.liamhosfeld.com/xml-namespaces/lima">'
    print '  <channel>'
    print '    <title>Lima Updates</title>'
    print "    <link>$(xml_escape "$release_url")</link>"
    print "    <item sparkle:version=\"$(xml_escape "$version")\" version=\"$(xml_escape "$version")\">"
    print "      <title>Lima $(xml_escape "$version")</title>"
    print "      <pubDate>$(xml_escape "$generated_at")</pubDate>"
    print "      <sparkle:releaseNotesLink>$(xml_escape "$release_url")</sparkle:releaseNotesLink>"
    print "      <enclosure url=\"$(xml_escape "$update_url")\" length=\"$update_bytes\" type=\"application/octet-stream\" sparkle:minimumSystemVersion=\"13.0\" lima:sha256=\"$update_sha\" lima:signatureStatus=\"pending-sparkle-signature\" />"
    print '    </item>'
    print '  </channel>'
    print '</rss>'
} > "$OUTPUT"
python3 - "$OUTPUT" <<'PY'
import sys
from xml.etree import ElementTree
ElementTree.parse(sys.argv[1])
PY
